<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
require APPPATH . 'libraries/REST_Controller.php';

class Users extends REST_Controller {

    function __construct()
    {
        // Construct the parent class
        parent::__construct();

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['Users_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['Users_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['Users_delete']['limit'] = 50; // 50 requests per hour per user/key
    }

    public function Users_get()
    {
        parse_str($_SERVER['QUERY_STRING'], $param);
        var_dump($param['login']);
        var_dump($param['token']);
        $this->load->model('Token_model');  

        if ($this->Token_model->verifyToken($param['login'],$param['token'])){

            $id = $this->get('id');
            
            // If the id parameter doesn't exist return all the Users
            $this->load->model('User_model');   
            if ($id == NULL)
            {        
                $UsersArray = $this->User_model->getData();
                if ($UsersArray == NULL)
                {
                    // Set the response and exit
                    $this->response([
                        'status' => FALSE,
                        'message' => 'No Users were found'
                    ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
                }
                else
                {
                    $this->response($UsersArray, REST_Controller::HTTP_OK);
                }
            }

            // Find and return a single record for a particular user.

            $id = (int) $id;

            // Validate the id.
            if ($id <= 0)
            {
                // Invalid id, set the response and exit.
                $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }

            // Get the user from the array, using the id as key for retrieval.
            // Usually a model is to be used for this.

            $tag = NULL;
            $Users = $this->User_model->getData();        
            if (!empty($Users))
            {
                foreach ($Users as $key => $value)
                {
                    if (isset($value['id']) && (int)$value['id'] === $id)
                    {
                        $tag = $value;
                    }
                }
            }
            
            if (!empty($tag))
            {
                $this->set_response($tag, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }
            else
            {
                $this->set_response([
                    'status' => FALSE,
                    'message' => 'Usuario(s) nao encontrada(s)'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }
        else
        {
            $this->set_response([
                'status' => FALSE,
                'message' => 'Usuario(s) nao encontrada(s)'
            ], REST_Controller::HTTP_NOT_FOUND); 
        }
    }

    public function Users_post()
    {        
        $this->load->model('User_model'); 
        $data = $this->post();
        // $json = file_get_contents('php://input');
        // $dataDecoded = html_entity_decode($json);
        // $data = json_decode($dataDecoded);
       
        // $this->some_model->update_user( ... );
        $result = $this->User_model->createUser($data);
        if ($result)
        {
            $message = [
                // 'id' => 100, // Automatically generated by the model
               'message' => 'Usuario adicionada.'
            ];   
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
        else
        {
            $message = [
                // 'id' => 100, // Automatically generated by the model
                'message' => 'Erro ao criar Usuario.'
            ]; 
            $this->set_response($message, REST_Controller::HTTP_BAD_REQUEST);
        }
    }
    
    public function Users_put()
    {
        
        $this->load->model('User_model'); 
        
        // // $this->some_model->update_user( ... );
        $data = $this->put();
        var_dump($data);
        if($this->User_model->updateUser($data)){
            $message = [
                'message' => 'Registro atualizado'
            ];
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }
        else
        {
            $message = [
                'message' => 'Não foi possível atualizar registro'
            ];
            $this->set_response($message, REST_Controller::HTTP_BAD_REQUEST); // CREATED (201) being the HTTP response code
        }

        
    }

    public function Users_delete()
    {
        $data = file_get_contents('php://input');
        $json = json_decode($data,true);
        $id = $json['id'];

        // Validate the id.
        if ($id <= 0)
        {
            $message = [            
                'message' => 'Registro invalido'
            ];
            // Set the response and exit
            $this->response($message, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            
        }
       
        $this->load->model('User_model'); 
        // $this->some_model->delete_something($id);

        if($this->User_model->deleteUser($json)){
            $message = [            
                'message' => 'Registro deletado'
            ];
            $this->set_response($message, REST_Controller::HTTP_OK);
        }
        else
        {
            $message = [            
                'message' => 'Nenhum registro deletado'
            ];
            $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
        }
    }

}
